### PR TITLE
fix: resolve import URL, pagination, and chat URL update bugs

### LINKED ISSUE #48: Fix import URL parsing, GitHub search pagination, and chat URL update
## Problem
Three user-visible bugs were found and reproduced with tests:
1. Import via GitHub link fails for clone URLs ending in .git.
2. GitHub repo search pagination omits per_page/page in OAuth path.
3. Project chat URL update is lost because reload happens before replaceState.

## Proposed Fix
- Strip .git suffix in repo parsing.
- Add per_page/page to search URL.
- Remove reload from URL update helper.

## Tests
- Added unit tests confirming each bug and passing after fix (vitest).
- Command: npm run test:run

## Environment
- OS: Linux Manjaro Gnome
- Node:  v25.2.1

### PR DESCRIPTION
**Pull request by nicolaspiet**
## Summary
- Strip .git from imported GitHub clone URLs
- Include pagination params in GitHub search API
- Avoid reload so chat URL updates persist

## Testing
- npm run test:run

Fixes #48

## Summary by CodeRabbit

* **Improvements**
  * Chat page now reloads immediately after creating a new chat to display the latest state.

### CODE REVIEW

File: src/app/project/[projectId]/page.tsx [hunk 1]
```diff
@@ -797,10 +798,7 @@ const ProjectPage = () => {
                 setMessages([]);
                 
                 // Update URL
-                window.location.reload();
-                const newUrl = new URL(window.location.href);
-                newUrl.searchParams.set('c', newChat.id.toString());
-                window.history.replaceState({}, '', newUrl.toString());
+                updateChatUrlWithReload(newChat.id.toString());
```
Comment (lak7) [inline src/app/project/[projectId]/page.tsx]: Instead of calling this function put all the logic here only. Therefore remove ProjectChatUrl.ts from lib

This will be the code to put here:
`const newUrl = new URL(window.location.href);
  newUrl.searchParams.set('c', newChat.id.toString());
  window.history.replaceState({}, '', newUrl.toString());
  window.location.reload();`

File: src/lib/github.ts [hunk 2]
```diff
@@ -0,0 +1,18 @@
+export function buildGithubReposUrl(params: {
```
Comment (lak7) [inline src/lib/github.ts]: Please address the potention issue by coderabbit

File: package-lock.json
Comment (lak7) [inline package-lock.json]: No change in this file

**Review by lak7 — CHANGES_REQUESTED** [review]
